[package]
name = "actix-web-min"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.7"
futures = "0.3.15"
tokio = "1.7.1"
